// A live Minecraft server instance. Spawns the real process, captures console,
// parses structured events (status, players, join/leave), and exposes control.
import { EventEmitter } from 'node:events';
import { spawn } from 'node:child_process';
import os from 'node:os';
import fs from 'node:fs';
import path from 'node:path';
import { config } from '../config.js';

const CONSOLE_BUFFER = 2000;

export const Status = {
  OFFLINE: 'offline',
  STARTING: 'starting',
  ONLINE: 'online',
  STOPPING: 'stopping',
  CRASHED: 'crashed',
};

export class McServer extends EventEmitter {
  constructor(record, dirs) {
    super();
    this.id = record.id;
    this.record = record;
    this.dirs = dirs;
    this.child = null;
    this.status = Status.OFFLINE;
    this.consoleBuffer = [];
    this.players = [];
    this.maxPlayers = 0;
    this.startedAt = 0;
    this.lastStatsAt = 0;
    this.cpuPercent = 0;
    this.memBytes = 0;
    this._statsTimer = null;
    this._listTimer = null;
    this._statSampleAt = 0;
    this._lastCpuTicks = 0;
  }

  get dir() { return this.dirs.serverDir; }

  setStatus(s) {
    if (this.status === s) return;
    this.status = s;
    this.emit('status', s);
  }

  pushConsole(line) {
    this.consoleBuffer.push(line);
    if (this.consoleBuffer.length > CONSOLE_BUFFER) this.consoleBuffer.shift();
    this.emit('console', line);
  }

  ensureServerProperties() {
    const r = this.record;
    const port = r.port || config.defaultPort;
    const propsPath = path.join(this.dir, 'server.properties');
    const wanted = {
      'server-port': String(port),
      'server-ip': config.serverBindHost,
      'max-players': String(r.maxPlayers || 20),
      'level-name': 'world',
      'motd': r.name || 'A Minecraft Server',
      'gamemode': r.gamemode || 'survival',
      'difficulty': r.difficulty || 'easy',
      'online-mode': String(Boolean(r.onlineMode !== false)),
      'pvp': String(Boolean(r.pvp !== false)),
      'enable-command-block': String(Boolean(r.commandBlocks)),
      'spawn-protection': String(r.spawnProtection || 0),
      'white-list': String(Boolean(r.whitelist)),
      'allow-nether': String(Boolean(r.allowNether !== false)),
      'view-distance': String(r.viewDistance || 10),
    };
    let existing = {};
    if (fs.existsSync(propsPath)) {
      const lines = fs.readFileSync(propsPath, 'utf8').split('\n');
      for (const ln of lines) {
        const m = ln.match(/^([^=#]+)=(.*)$/);
        if (m) existing[m[1].trim()] = m[2].trim();
      }
    }
    const merged = { ...wanted, ...existing };
    const out = Object.entries(merged).map(([k, v]) => `${k}=${v}`).join('\n') + '\n';
    fs.writeFileSync(propsPath, out);
  }

  writeEula() {
    fs.writeFileSync(path.join(this.dir, 'eula.txt'),
      '# Generated by mc-control-manager\n' + (this.record.acceptEula ? 'eula=true\n' : 'eula=false\n'));
    if (!this.record.acceptEula) {
      throw new Error('EULA not accepted. Enable acceptEula in server settings to start.');
    }
  }

  buildArgs() {
    const r = this.record;
    const mem = Math.min(r.memoryMb || config.defaultMemoryMb, config.maxMemoryMb);
    const jar = this.dirs.jarPath;
    const java = r.javaBin || config.javaBin;
    const args = [
      `-Xms${mem}M`, `-Xmx${mem}M`,
      '-XX:+UseG1GC',
      '-XX:+ParallelRefProcEnabled',
      '-XX:MaxGCPauseMillis=200',
    ];
    if (r.jvmArgs && Array.isArray(r.jvmArgs)) args.push(...r.jvmArgs);
    args.push('-jar', jar, '--nogui');
    if (r.extraArgs && Array.isArray(r.extraArgs)) args.push(...r.extraArgs);
    return { bin: java, args, bedrock: false };
  }

  async start() {
    if (this.child) throw new Error('Server already running');
    const jarPath = this.dirs.jarPath;
    if (!fs.existsSync(jarPath)) {
      throw new Error(`Server jar not found: ${jarPath}. Install a software version first.`);
    }
    this.ensureServerProperties();
    this.writeEula();

    this.setStatus(Status.STARTING);
    const { bin, args } = this.buildArgs();
    const spawnOpts = { cwd: this.dir, env: { ...process.env }, stdio: ['pipe', 'pipe', 'pipe'] };

    try {
      this.child = spawn(bin, args, spawnOpts);
    } catch (e) {
      this.setStatus(Status.CRASHED);
      throw e;
    }
    this.startedAt = Date.now();
    this.child.stdout.setEncoding('utf8');
    this.child.stderr.setEncoding('utf8');

    this.child.stdout.on('data', (d) => this._onData(d));
    this.child.stderr.on('data', (d) => this._onData(d));
    this.child.on('error', (err) => {
      this.pushConsole(`[manager] spawn error: ${err.message}`);
      this.setStatus(Status.CRASHED);
    });
    this.child.on('exit', (code, signal) => this._onExit(code, signal));

    this._startStats();
    this.emit('start');
    return { status: this.status };
  }

  _onData(chunk) {
    const lines = chunk.split(/\r?\n/);
    for (const line of lines) {
      if (!line) continue;
      this.pushConsole(line);
      this._parseLine(line);
    }
  }

  _parseLine(line) {
    const join = line.match(/\[.*?\] \[.*?\/INFO\]: (\w+) joined the game/);
    const left = line.match(/\[.*?\] \[.*?\/INFO\]: (\w+) left the game/);
    if (join) {
      if (!this.players.includes(join[1])) this.players.push(join[1]);
      this.emit('players', this.players.slice());
    } else if (left) {
      this.players = this.players.filter((p) => p !== left[1]);
      this.emit('players', this.players.slice());
    }
    if (line.includes('Done') && line.includes('For help')) {
      this.setStatus(Status.ONLINE);
      this._startListPolling();
    }
    if (line.includes('Starting minecraft server version')) {
      this._startListPolling();
    }
    // Server is reachable once it starts reporting player counts (post-world-gen).
    if (line.includes('There are') && line.includes('players online')) {
      if (this.status !== Status.ONLINE) this.setStatus(Status.ONLINE);
      this._startListPolling();
    }
  }

  _startListPolling() {
    if (this._listTimer) return;
    this._listTimer = setInterval(() => {
      if (this.child && this.child.stdin.writable) {
        try { this.child.stdin.write('list\n'); } catch {}
      }
    }, 5000);
    this._listTimer.unref && this._listTimer.unref();
  }

  _startStats() {
    if (this._statsTimer) return;
    this._statsTimer = setInterval(() => this._sampleStats(), 2000);
    this._statsTimer.unref && this._statsTimer.unref();
  }

  _sampleStats() {
    if (!this.child || !this.child.pid) return;
    const pid = this.child.pid;
    let cpu = 0;
    let memBytes = 0;
    // Read the child process's own usage from /proc (Linux). Fall back to the
    // manager's own metrics if /proc is unavailable (non-Linux hosts).
    try {
      const stat = fs.readFileSync(`/proc/${pid}/stat`, 'utf8');
      const fields = stat.split(' ');
      const utime = Number(fields[13]) || 0; // clock ticks in user mode
      const stime = Number(fields[14]) || 0; // clock ticks in kernel mode
      const startTime = Number(fields[21]) || 0;
      const ticks = (os.cpus().length || 1) * 100; // Linux CLK_TCK = 100
      const now = Date.now();
      const elapsedMs = now - this._statSampleAt;
      if (this._statSampleAt && elapsedMs > 0) {
        const deltaTicks = (utime + stime) - (this._lastCpuTicks || 0);
        cpu = Math.min(100, (deltaTicks / (elapsedMs / 1000)) / ticks * 100);
      }
      this._lastCpuTicks = utime + stime;
      this._statSampleAt = now;

      const status = fs.readFileSync(`/proc/${pid}/status`, 'utf8');
      const vm = status.match(/^VmRSS:\s+(\d+)\s+kB$/m);
      memBytes = vm ? Number(vm[1]) * 1024 : 0;
    } catch {
      const usage = process.cpuUsage();
      cpu = (usage.user + usage.system) / 1e6;
      memBytes = process.memoryUsage().heapUsed;
    }
    this.cpuPercent = Number(cpu.toFixed(1));
    this.memBytes = memBytes;
    this.lastStatsAt = Date.now();
    this.emit('stats', this.stats());
  }

  stats() {
    return {
      status: this.status,
      players: this.players.length,
      maxPlayers: this.maxPlayers,
      uptimeMs: this.startedAt ? Date.now() - this.startedAt : 0,
      cpuPercent: this.cpuPercent,
      memBytes: this.memBytes,
      pid: this.child ? this.child.pid : null,
    };
  }

  async stop(force = false) {
    if (!this.child) return { status: this.status };
    if (force) {
      this.child.kill('SIGKILL');
    } else {
      this.setStatus(Status.STOPPING);
      try { this.child.stdin.write('stop\n'); } catch {}
      const t = setTimeout(() => {
        if (this.child) this.child.kill('SIGTERM');
      }, 15000);
      t.unref && t.unref();
    }
    return { status: this.status };
  }

  async restart() {
    await this.stop();
    await new Promise((res) => {
      const t = setInterval(() => {
        if (!this.child) { clearInterval(t); res(); }
      }, 500);
      setTimeout(() => { clearInterval(t); res(); }, 20000);
    });
    return this.start();
  }

  sendCommand(cmd) {
    if (!this.child || !this.child.stdin.writable) throw new Error('Server not running');
    this.child.stdin.write(cmd + '\n');
    return { ok: true };
  }

  _onExit(code, signal) {
    if (this._statsTimer) clearInterval(this._statsTimer);
    if (this._listTimer) clearInterval(this._listTimer);
    const wasOnline = this.status === Status.ONLINE || this.status === Status.STOPPING;
    this.child = null;
    this.players = [];
    this.setStatus(Status.OFFLINE);
    this.emit('stop', { code, signal, expectedStop: wasOnline });
  }

  destroy() {
    if (this.child) { try { this.child.kill('SIGKILL'); } catch {} }
  }
}
